/**
 * **The interface copy this API writes itself, rather than leaving to the web tier.**
 *
 * One deliberate exception sits outside this module and is named here so the boundary is not a
 * claim a reader has to take on trust: `lib/rush.ts` holds `RUSH_NOTES`, six Russian sentences a
 * simulated guest leaves on an order. Those are not copy this product says - they are text a
 * guest typed, generated by the demo and carried verbatim to a cook the way a real note would be,
 * so they belong with the simulation that invents them. Interface copy is what lives here, and a
 * grep for a Cyrillic literal under `apps/api/src` outside a test finds these two files and no
 * others.
 *
 * Almost nothing belongs here, and that is the point. Every sentence this service says to a guest
 * or to a member of staff travels as an `ErrorMessageKey` and is worded by
 * `apps/web/messages/ru.json`; `lib/errors.ts` explains why, and an English `message` beside the
 * key is for a developer reading a log. The strings below are the exceptions, and they are
 * exceptions for one reason each time: **something other than the web tier draws them.** Stripe
 * prints the checkout line on its own hosted page; pdfkit prints the sheet onto paper. Neither asks
 * the web for words, so neither can be reached by the web's dictionary, and this app cannot import
 * it — a Fastify service does not read a Next app's messages.
 *
 * `lib/payments.ts` used to carry the first of these alone, with a note saying that a second one
 * appearing would turn the note into a dictionary. Task 13 added six, so this is that dictionary:
 * one module, plain constants, no loader and no locale lookup. There is exactly one locale to
 * serve, and inventing a mechanism for it would be inventing a second i18n system for seven
 * strings.
 *
 * All of it is written against `docs/design/02b-copy-ru.md`, which outranks any wording here:
 * «стол», never «столик» or «таблица»; «QR-код», never «QR код»; «ё» is used; «—» for dashes and
 * «ёлочки» for quotes. Non-breaking spaces are written as `\u00a0` escapes rather than pasted, so
 * they are visible in the source and survive a diff.
 */

/** `2026-09-14` as a Russian reader writes a date. */
const asRussianDate = (isoDay: string): string => isoDay.split('-').reverse().join('.');

/**
 * The name of the single line item on Stripe's hosted Checkout page, beside the amount — the last
 * thing a guest reads before paying.
 *
 * Worded to match `guest.pay.terminalHeading`, which is what the demo terminal shows the same guest
 * for the same order — «Стол 7 · Заказ № 12» — so switching a deployment from the demo provider to
 * Stripe does not change what the payment step is called.
 *
 * **That match is unguarded, and cannot be guarded from here.** `payments.test.ts` pins this string
 * and pins that `startPayment` hands it to the provider, but nothing compares it with
 * `guest.pay.terminalHeading`: this app cannot import the web's dictionary, which is the same
 * reason the string lives here at all. If the terminal's heading is reworded, reword this too — a
 * reviewer is what stands between them, not a test.
 */
export const checkoutLineName = (order: { number: number; tableNumber: number }): string =>
  `Стол\u00a0${order.tableNumber} · Заказ №\u00a0${order.number}`;

/**
 * The printed QR sheet: the one surface of this product a guest physically holds, and the only one
 * the web tier has no part in. `lib/qr-pdf.ts` draws these onto A4 with pdfkit and an embedded
 * brand face; `qr-pdf.test.ts` reads them back out of the bytes the way a PDF reader does.
 */
export const qrSheet = {
  /** The document's `/Title`: what a reader puts in its window and a printer on the job. */
  title: (restaurant: string): string => `${restaurant} — QR-коды столов`,
  /** The running head, opposite the restaurant's name. */
  printedOn: (isoDay: string): string => `QR-коды столов — напечатано ${asRussianDate(isoDay)}`,
  /**
   * A card's heading. The non-breaking space is the copy contract's — it binds the number to the
   * noun — and it is the same binding `admin.tables.table` makes on screen, so the card on the
   * table and the row in the admin name the table identically.
   */
  table: (number: number): string => `Стол\u00a0${number}`,
  /**
   * **The sentence a guest reads off the card**, and the reason this task existed: it was English,
   * and the face it was set in could not have drawn it in Russian. The verbs are the landing
   * page's — «выберите блюда и оформите заказ» — because a guest who read the site and a guest who
   * only sat down are being told to do the same thing.
   */
  instruction: 'Отсканируйте код камерой телефона, выберите блюда и оформите заказ.',
  /**
   * An empty sheet. An invitation, per the copy contract, rather than a statement of absence, and
   * it ends on the admin's own noun for this document: `admin.tables.printQr` is «Распечатать
   * QR-коды» and `admin.qr.reissued` ends «Распечатайте QR-коды заново», three lines away in the
   * dictionary. «лист» is accurate Russian for a sheet of paper and a word this product uses
   * nowhere else, which is reason enough not to introduce it on the one surface a guest holds.
   */
  nothingToPrint: 'Добавьте стол или включите отключённый — и распечатайте QR-коды заново.',
  /**
   * The downloaded file's name. The header carries an ASCII `filename` beside this one, which
   * `routes/tables.ts` builds from the same stem and the same day, so the two differ by the one
   * translated word and nothing else: a client that honours only the fallback saves the same file
   * under the same date, not a different-looking one. The day stays ISO for that reason - a
   * filename is sorted more often than it is read aloud, and the copy contract governs sentences.
   */
  fileName: (slug: string, isoDay: string): string => `${slug}-QR-коды-${isoDay}.pdf`,
} as const;
